#!/bin/bash
set -a

export GHCICD_VERSION=0.0.1
export GHCICD_VERBOSE=0
export GHCICD_DEBUG=0
export GHCICD_OUTPUT_X=0
export GHCICD_PATH_LIB="$GHCICD_PATH_SRC/lib"
export GHCICD_PATH_CMD="$GHCICD_PATH_SRC/cmd"

