blank_issues_enabled: true
contact_links:
  - name: Repo issues
    url: https://github.com/mkungla/github-cicd-experiments/issues/new/choose
    about: Report new issues here
  - name: Security issue
    url: https://github.com/mkungla/github-cicd-experiments/blob/main/.github/SECURITY.md
    about: Please report security vulnerabilities here.