blank_issues_enabled: true
contact_links:
  - name: Have a question?
    url: https://github.com/mkungla/github-cicd-experiments/discussions/new
    about: Search for discussions or ask your question under discussions

