name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10 # do fetch-dept handle tags?

    - name: Get latest
      run: git fetch --all

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
        cache-dependency-path: .github/package-lock.json

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Install action dependencies
      working-directory: ./.github
      run: npm ci

    - name: (cmd) GO Generate
      working-directory: ./cmd/github-cicd-experiments
      run: go generate ./...

    - name: update tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: update repo files for tag
      run: .github/actions-scripts/commit.js
