name: 'Issue Cron'

permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has no activity for a while'
          stale-pr-message: 'This PR has no activity for a while'
          days-before-stale: 60
          days-before-close: 14
          close-issue-message: 'This issue was closed since there was no activity after it was marked stale'
          close-pr-message: 'This PR was closed since there was no activity after it was marked stal'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          remove-stale-when-updated: true
          labels-to-add-when-unstale: 'triage'
