name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10 # do fetch-dept handle tags?
      - name: Get tag
        run: git fetch
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: GO Generate
        working-directory: ./cmd/github-cicd-experiments
        run: go generate ./...
  tag:
    needs: [go]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
        cache-dependency-path: .github/package-lock.json
    - name: Install dependencies
      working-directory: ./.github
      run: npm ci
    - name: update tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: update repo files for tag
      run: .github/actions-scripts/commit.js
