on:
  workflow_run:
    workflows:
      - .github/workflows/github-tag.yml
    types:
      - completed
    tags:
      - 'v*'

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "tagging done"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "tagging failed"
