# catch repo events not tested yet
name: honeycomb

on:
  # Events that trigger workflows
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  # issue_comment                 ./issues.yml
  # issues                        ./issues.yml
  # label:                        ./labels.yml
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  # push:                         ./push.yml
  registry_package:
  release:
  status:
  watch:
  workflow_run:
    workflows: ["test"]
    types: [completed]
  # manual
  repository_dispatch:
  workflow_dispatch:

  # Webhook events and payloads which can nopt be used in workflows
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#code_scanning_alert
  # Potentially catch other webhook events
  # - code_scanning_alert is not a valid event name
  # - content_reference is not a valid event name
  # - deploy_key is not a valid event name
  # - github_app_authorization is not a valid event name
  # - installation is not a valid event name
  # - installation_repositories is not a valid event name
  # - marketplace_purchase is not a valid event name
  # - member is not a valid event name
  # - membership is not a valid event name
  # - meta is not a valid event name
  # - organization is not a valid event name
  # - org_block is not a valid event name
  # - package is not a valid event name
  # - ping is not a valid event name
  # - repository is not a valid event name
  # - repository_import is not a valid event name
  # - repository_vulnerability_alert is not a valid event name
  # - secret_scanning_alert is not a valid event name
  # - security_advisory is not a valid event name
  # - sponsorship is not a valid event name
  # - star is not a valid event name
  # - team is not a valid event name
  # - team_add is not a valid event name

jobs:
  catch:
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: |
          echo "${{ toJSON(github.event) }}"
          exit 1
