# https://github.com/mkungla/github-cicd/discussions/11
name: issues
on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned

  # https://github.com/mkungla/github-cicd/discussions/11#discussioncomment-1233633
  issue_comment:
    types:
      - created
      - deleted
      - edited

# default-steps:
#   - run: echo ${{ toJSON(github) }}
#   - run: echo ${{ toJSON(env) }}
#   - run: echo ${{ toJSON(job) }}
#   - run: echo ${{ toJSON(steps) }}
#   - run: echo ${{ toJSON(runner) }}
#   - run: echo ${{ toJSON(needs) }}


jobs:
  not-a-pull-request:
    if: github.event_name === 'issues' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "issue #${{ github.event.issue.number }} pull_request #${{ github.event.issue.pull_request }}"
          exit 1

  issue:
    if: github.event_name === 'issues' && matrix.event == github.event.action
    strategy:
      matrix:
        event:
          - opened
          - edited
          - deleted
          - transferred
          - pinned
          - unpinned
          - closed
          - reopened
          - assigned
          - unassigned
          - labeled
          - unlabeled
          - locked
          - unlocked
          - milestoned
          - demilestoned
    steps:
      - run: |
          echo "issue #${{ github.event.issue.number }} pull_request #${{ github.event.issue.pull_request }}"
          exit 1

  # opened:
  #   if: github.event.action == 'opened'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # edited:
  #   if: github.event.action == 'edited'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # deleted:
  #   if: github.event.action == 'deleted'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # transferred:
  #   if: github.event.action == 'transferred'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # pinned:
  #   if: github.event.action == 'pinned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # unpinned:
  #   if: github.event.action == 'unpinned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # closed:
  #   if: github.event.action == 'closed'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # reopened:
  #   if: github.event.action == 'reopened'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # assigned:
  #   if: github.event.action == 'assigned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # unassigned:
  #   if: github.event.action == 'unassigned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # labeled:
  #   if: github.event.action == 'labeled'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # unlabeled:
  #   if: github.event.action == 'unlabeled'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # locked:
  #   if: github.event.action == 'locked'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # unlocked:
  #   if: github.event.action == 'unlocked'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # milestoned:
  #   if: github.event.action == 'milestoned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  # demilestoned:
  #   if: github.event.action == 'demilestoned'
  #   steps:
  #     - run: |
  #         echo "${{ github.event.sender.login }} triggered ${{ github.event.action }} issue #${{ github.event.issue.number }}"

  issue-comment:
    name: Issue comment
    if: github.event_name === 'issue_comment' && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - if: github.event.action == 'created'
        run: |
          echo "${{ github.event.sender.login }} commented on issue #${{ github.event.issue.number }}"
      - if: github.event.action == 'deleted'
        run: |
          echo "${{ github.event.sender.login }} deleted comment on issue #${{ github.event.issue.number }}"
      - if: github.event.action == 'edited'
        run: |
          echo "${{ github.event.sender.login }} edited comment on issue #${{ github.event.issue.number }}"
