# https://github.com/mkungla/github-cicd/discussions/11
on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned

  # https://github.com/mkungla/github-cicd/discussions/11#discussioncomment-1233633
  issue_comment:
    types:
      - created
      - deleted
      - edited

jobs:
  not-a-pull-request:
    if: github.event_name === 'issues' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "issue #${{ github.event.issue.number }} pull_request #${{ github.event.issue.pull_request }}"
          exit 1

  opened:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    run: |
          echo "${{ github.event.sender.login }} opened issue #${{ github.event.issue.number }}"

  edited:
    runs-on: ubuntu-latest
    if: github.event.action == 'edited'
    run: |
          echo "${{ github.event.sender.login }} edited issue #${{ github.event.issue.number }}"

  deleted:
    runs-on: ubuntu-latest
    if: github.event.action == 'deleted'
    run: |
          echo "${{ github.event.sender.login }} deleted issue #${{ github.event.issue.number }}"

  transferred:
    runs-on: ubuntu-latest
    if: github.event.action == 'transferred'
    run: |
          echo "${{ github.event.sender.login }} transferred issue #${{ github.event.issue.number }}"

  pinned:
    runs-on: ubuntu-latest
    if: github.event.action == 'pinned'
    run: |
          echo "${{ github.event.sender.login }} pinned issue #${{ github.event.issue.number }}"

  unpinned:
    runs-on: ubuntu-latest
    if: github.event.action == 'unpinned'
    run: |
          echo "${{ github.event.sender.login }} unpinned issue #${{ github.event.issue.number }}"

  closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    run: |
          echo "${{ github.event.sender.login }} closed issue #${{ github.event.issue.number }}"

  reopened:
    runs-on: ubuntu-latest
    if: github.event.action == 'reopened'
    run: |
          echo "${{ github.event.sender.login }} reopened issue #${{ github.event.issue.number }}"

  assigned:
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    run: |
          echo "${{ github.event.sender.login }} assigned issue #${{ github.event.issue.number }}"

  unassigned:
    runs-on: ubuntu-latest
    if: github.event.action == 'unassigned'
    run: |
          echo "${{ github.event.sender.login }} unassigned issue #${{ github.event.issue.number }}"

  labeled:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled'
    run: |
          echo "${{ github.event.sender.login }} labeled issue #${{ github.event.issue.number }}"

  unlabeled:
    runs-on: ubuntu-latest
    if: github.event.action == 'unlabeled'
    run: |
          echo "${{ github.event.sender.login }} unlabeled issue #${{ github.event.issue.number }}"

  locked:
    runs-on: ubuntu-latest
    if: github.event.action == 'locked'
    run: |
          echo "${{ github.event.sender.login }} locked issue #${{ github.event.issue.number }}"

  unlocked:
    runs-on: ubuntu-latest
    if: github.event.action == 'unlocked'
    run: |
          echo "${{ github.event.sender.login }} unlocked issue #${{ github.event.issue.number }}"

  milestoned:
    runs-on: ubuntu-latest
    if: github.event.action == 'milestoned'
    run: |
          echo "${{ github.event.sender.login }} milestoned issue #${{ github.event.issue.number }}"

  demilestoned:
    runs-on: ubuntu-latest
    if: github.event.action == 'demilestoned'
    run: |
          echo "${{ github.event.sender.login }} demilestoned issue #${{ github.event.issue.number }}"

  issue-comment:
    name: Issue comment
    if: github.event_name === 'issue_comment' && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - if: github.event.action == 'created'
        run: |
          echo "${{ github.event.sender.login }} commented on issue #${{ github.event.issue.number }}"
      - if: github.event.action == 'deleted'
        run: |
          echo "${{ github.event.sender.login }} deleted comment on issue #${{ github.event.issue.number }}"
      - if: github.event.action == 'edited'
        run: |
          echo "${{ github.event.sender.login }} edited comment on issue #${{ github.event.issue.number }}"
