name: publish
on:
  workflow_dispatch:
    inputs:
      changeLog:
        description: 'change Log'
        required: true
        default: ''
jobs:
  chlog:
  runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub env
        run: |
          echo "${{ github.event.inputs.changeLog }}!" >> cl.md
          cat cl.md
