# https://github.com/mkungla/github-cicd/discussions/124
name: push
on:
  push:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  
  deploy_backend_staging:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  deploy_frontend_staging:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    needs:
     - deploy_backend_staging
     - deploy_frontend_staging
    if: |
      always() &&
      contains(needs.*.result, 'success') &&
      !contains(needs.*.result, 'failure')
    steps:
      - run: exit 0
