# https://github.com/mkungla/github-cicd/discussions/124
name: push
on:
  push:

jobs:
  wait:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16', '1.17', '1.18.0-rc1']
    steps:
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: false
      - run: go version
  go:
    runs-on: ubuntu-latest
    steps:
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.18.0-beta2'
          stable: false
      - run: go version

  deploy_backend_staging-1:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  deploy_frontend_staging-1:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  e2e-test-1:
    runs-on: ubuntu-latest
    needs:
     - deploy_backend_staging-1
     - deploy_frontend_staging-1
    if: |
      always() &&
      contains(needs.*.result, 'success') &&
      contains(needs.*.result, 'skipped')
    steps:
      - run: echo "${{ toJSON(needs) }}"
      - run: echo "this should never run"
      - run: exit 1

  deploy_backend_staging-2:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  deploy_frontend_staging-2:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  e2e-test-2:
    runs-on: ubuntu-latest
    needs:
     - deploy_backend_staging-2
     - deploy_frontend_staging-2
    if: |
      always() &&
      contains(needs.*.result, 'success') &&
      contains(needs.*.result, 'skipped')
    steps:
      - run: echo "${{ toJSON(needs) }}"
      - run: echo "any success ${{ contains(needs.*.result, 'success') }}"
      - run: echo "any skipped ${{ contains(needs.*.result, 'skipped') }}"
      - run: exit 0
