# https://github.com/mkungla/github-cicd/discussions/124
name: push
on:
  push:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  
  deploy_backend_staging-1:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  deploy_frontend_staging-1:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  e2e-test-1:
    name: e2e-test
    runs-on: ubuntu-latest
    needs:
     - deploy_backend_staging-1
     - deploy_frontend_staging-1
    if: |
      always() &&
      toJSON(contains(needs.*.result, 'success')) &&
      !toJSON(contains(needs.*.result, 'failure'))
    steps:
      - run: echo "${{ toJSON(needs) }}"
      - run: echo "any success ${{ contains(needs.*.result, 'success') }}"
      - run: echo "any skipped ${{ contains(needs.*.result, 'skipped') }}"
      - run: exit 1
  
  deploy_backend_staging-2:
    needs: wait
    if: false # force to skip
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  deploy_frontend_staging-2:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  e2e-test-2:
    name: e2e-test
    runs-on: ubuntu-latest
    needs:
     - deploy_backend_staging-2
     - deploy_frontend_staging-2
    if: |
      always() &&
      toJSON(contains(needs.*.result, 'success')) &&
      !toJSON(contains(needs.*.result, 'failure'))
    steps:
      - run: echo "${{ toJSON(needs) }}"
      - run: echo "any success ${{ contains(needs.*.result, 'success') }}"
      - run: echo "any skipped ${{ contains(needs.*.result, 'skipped') }}"
      - run: exit 1
