# https://github.com/mkungla/github-cicd/discussions/124
name: push
on:
  push:

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success always"
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "this will never run"
  C:
    runs-on: ubuntu-latest
    steps:
      - run: |
          exho "here to fail"
          exit 1

  D:
    runs-on: ubuntu-latest
    needs: [A, B, C]
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
      !contains(needs.*.result, 'failure')
    steps:
      - run: echo "${{ toJSON(needs) }}"
