name: "Update README.md"

on:
  push:
    branches: [ main ]
    paths:
      - README.md
      - .github/actions-scripts/update-readme.js
      - .github/workflows/readme-update.yml
      - cmd/github-cicd-experiments/internal/assets/readme.yml
      - cmd/github-cicd-experiments/cmd/readme.go
      - cmd/github-cicd-experiments/internal/readme
  pull_request:
    branches: [ main ]
    paths:
      - README.md
      - .github/actions-scripts/update-readme.js
      - .github/workflows/readme-update.yml
      - cmd/github-cicd-experiments/internal/assets/readme.yml
      - cmd/github-cicd-experiments/cmd/readme.go
      - cmd/github-cicd-experiments/internal/readme

jobs:
  checks:
    if: github.repository == 'mkungla/github-cicd-experiments'
    runs-on: ubuntu-latest
    name: Check README config
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - run: if [ $(git diff --name-only refs/heads/main refs/heads/main~1 | grep README.md | wc -m) -gt 0 ]; then echo "::error ile=README.md::Do not edit README directly"; echo "::debug::update cmd/github-cicd-experiments/internal/assets/readme.yml instead" exit 1; fi
  update:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: .github/package-lock.json
      - name: Install dependencies
        working-directory: ./.github
        run: npm ci
      - name: generate new README
        working-directory: ./cmd/github-cicd-experiments
        run: go run . readme update
      # only on push to repo create actual commit
      - name: push new readme
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/actions-scripts/update-readme.js
