on:
  # uns your workflow anytime the issue_comment event occurs.
  # More than one activity type triggers this event.
  # For information about the REST API, see
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
  issue_comment:
    types:
      - created
      # - deleted
      # - edited

jobs:
  issue-comment:
    name: Issue comment
    if: guithub.event_name === 'issue_comment' && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.sender.login }} commented on issue #${{ github.event.issue.number }}"

  pull-request-comment:
    name: Pull request comment
    if: guithub.event_name === 'issue_comment' && github.event.issue.pull_request
    steps:
      - run: |
          echo "${{ github.event.sender.login }} commented on pull request #${{ github.event.issue.number }}"

  # if: contains(github.event.issue.labels.*.name, 'question')
