on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub env
        run: |
          echo "::group::github"
          echo "${{ toJSON(github) }}"
          echo "::endgroup::"

          echo "::group::GITHUB"
          env | grep '^GITHUB'
          echo "::endgroup::"

          echo "::group::RUNNER"
          env | grep '^RUNNER'
          echo "::endgroup::"

          echo "::group::GITHUB_ENV"
          cat $GITHUB_ENV
          echo "::endgroup::"

          echo "::group::env"
          env
          echo "::endgroup::"

      - name: Dump job context
        run: echo "${{ toJSON(env) }}"
      - name: Dump steps context
        run: echo "${{ toJSON(env) }}"
      - name: Dump runner context
        run: echo "${{ toJSON(env) }}"
      - name: Dump env context
        run: echo "${{ toJSON(env) }}"
      - name: Dump needs context
        run: echo "${{ toJSON(needs) }}"
      - name: Dump needs context
        run: echo "${{ toJSON(steps) }}"
      - name: Dump strategy context
        run: echo "${{ toJSON(strategy) }}"
      - name: Dump matrix context
        run: echo "${{ toJSON(matrix) }}"
  clog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Log
        id: getLog
        run: |
          CHANGELOG="$(cat test.md)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=changeLog::${{ toJSON(CHANGELOG)}}"
      - name: Invoke CLI workflow with changelog
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Workflow publish
          token: ${{ secrets.TOKEN }}
          repo: mkungla/github-cicd
          inputs: '{ "changeLog": "${{steps.getLog.outputs.changeLog}}"}'
