on:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub env
        run: |
          echo "::group::github"
          echo "${{ toJSON(github) }}"
          echo "::endgroup::"

          echo "::group::GITHUB"
          env | grep '^GITHUB'
          echo "::endgroup::"

          echo "::group::RUNNER"
          env | grep '^RUNNER'
          echo "::endgroup::"

          echo "::group::GITHUB_ENV"
          cat $GITHUB_ENV
          echo "::endgroup::"

          echo "::group::env"
          env
          echo "::endgroup::"

      - name: Dump job context
        run: echo "${{ toJSON(env) }}"
      - name: Dump steps context
        run: echo "${{ toJSON(env) }}"
      - name: Dump runner context
        run: echo "${{ toJSON(env) }}"
      - name: Dump env context
        run: echo "${{ toJSON(env) }}"
      - name: Dump needs context
        run: echo "${{ toJSON(needs) }}"
      - name: Dump needs context
        run: echo "${{ toJSON(steps) }}"
      - name: Dump strategy context
        run: echo "${{ toJSON(strategy) }}"
      - name: Dump matrix context
        run: echo "${{ toJSON(matrix) }}"

  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success always"
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "this will never run"
  C:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          exho "here to fail"
          exit 1

  D:
    runs-on: ubuntu-latest
    needs: [A, B, C]
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
    env:
      SLACK_COLOR: "${{ contains(needs.*.result, 'failure') && 'danger' || 'good' }}"
    steps:
      - run: echo $SLACK_COLOR
      - run: echo "${{ toJSON(needs) }}"
