on:
  push:

jobs:
  data:
    runs-on: ubuntu-latest
    # defaults:
    #   run: |
    #     echo "ISSUE_URL=$" >> $GITHUB_ENV
    steps:
      - run: node --version
      - id: set-out-for-job
        with:
          entrypoint: /bin/echo
          args: The ${{ github.event_name }} event triggered this step.
        run: |
          echo "::save-state name=fnSaveState::12345"
          echo '::set-output name=fnSetOutput::67890'
          echo "fnSetEnv=123456" >> $GITHUB_ENV


      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo "$ENV_CONTEXT"
