on:
  push:

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::save-state name=fnSaveState::12345"
          echo '::set-output name=fnSetOutput::67890'



      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo "$ENV_CONTEXT"

  stale:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/stale/pull/554
      - uses: mkungla/stale@main
        with:
          days-before-issue-stale: 1
          days-before-issue-close: 1
          stale-issue-message: 'This issue has no activity for a while.'
          close-issue-message: 'This issue was closed since there was no activity after it was marked stale.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug'
          remove-issue-stale-when-updated: true
          labels-to-add-when-unstale: 'triage'
          exempt-all-issue-milestones: true
          days-before-pr-stale : -1
          days-before-pr-close: -1
